### PR TITLE
Update to Avalonia 0.10

### PR DESCRIPTION
**Pull request by FoggyFinder**
There are a lot of breaking changes and I don't think I can handle all of them:

* [x] `DatePicker` -> `CalendarDatePicker`
* [x] `Avalonia.Diagnostics` now is a separate package.
* [ ] `Styles` is turned to a read-only. My current understanding of project doesn't allow to fix it. I've tried to avoid compile errors though.
* [x] `Examples.MusicPlayer` is broken with these changes. I suppose because of `Citrus.Avalonia`.
* [x] `IInteractive.AddHandler` now returns `unit` I've used `AddDisposableHandler` ~for now but I'm not sure whether it correct or not.~ From gitter:
> call `AddDisposableHandler` if you need a disposable
* [ ] `.SetValue` returns `IDisposable`. I've used `ignore` function to have ability to compile temporarily.
* [x] Review old controls and add missing properties.
  - * [x] ComboBox.VerticalContentAlignment
  - * [x] ComboBox.HorizontalContentAlignment
  - * [x] TextBlock.MaxLines
  - * [x] Border.BoxShadow
  - * [x] Track.IgnoreThumbDrag
  - * [x] ProgressBar.ShowProgressText
  - * [x] Slider.TickPlacement
  - * [x] Slider.Ticks
  - * [x] ContentPresenter.BoxShadow
  - * [x] ScrollBar.AllowAutoHide
  - * [x] ScrollBar.IsExpanded
  - * [x] SelectingItemsControl.Selection
  - * [x] TextBox.HorizontalContentAlignment
  - * [x] TextBox.VerticalContentAlignment
  - * [x] TextBlock.LineHeight
  - * [x] TextBlock.Padding
  - * [x] TextBlock.TextDecorations
  - * [x] TextBlock.TextTrimming
  - * [x] ScrollViewer.AllowAutoHide
  - * [x] ScrollViewer.IsExpanded
  - * [x] ScrollViewer.LargeChange
  - * [x] ScrollViewer.SmallChange
  - * [x] ScrollViewer.ScrollChangedEvent
  - * [x] Popup.PlacementAnchor
  - * [x] Popup.PlacementConstraintAdjustment
  - * [x] Popup.PlacementGravity
  - * [x] Popup.PlacementRect
  - * [x] Popup.WindowManagerAddShadowHintProperty
* [ ] Check new panels/controls and add them accordingly.
   - * [x] SplitView
   - * [x] DatePicker 
   - * [x] TimePicker
   - * [x] ToggleSwitch
   - * [ ] RelativePanel
   - * [x] TickBar
* [x] `Fluent` theme.
* [ ] Add [`IRecyclingDataTemplate`](https://github.com/AvaloniaUI/Avalonia/pull/4271) to `DataTemplateView` ?

### CODE REVIEW

**Comment by JaggerJo** [comment]
I have a working hacks local version - but let's do it in a clean way here!

**Comment by AngelMunoz** [comment]
I'm working to fix (at least my own mess 😁) the player sample on @FoggyFinder 's fork I'm getting this
image
any idea @JaggerJo ?

**Comment by AngelMunoz** [comment]
psh nevermind wrong branch

**Comment by JaggerJo** [comment]
Just for reference https://www.fuget.org/packages/Avalonia/0.10.0-preview1/lib/netstandard2.0/diff/0.9.11/

**Comment by JaggerJo** [comment]
@FoggyFinder thanks for all the work! I currently can't contribute that much myself - so thanks a lot

**Comment by FoggyFinder** [comment]
More than happy to do something useful :-)

The 2 big issues that remains:

a) `Styles` - dunno how to handle it
b) `RelativePanel` - requires additional changes to support references to other controls. So probably it makes sense to move this out of the PR.

**Comment by JaggerJo** [comment]
> More than happy to do something useful :-)
> 
> The 2 big issues that remains:
> 
> a) `Styles` - dunno how to handle it
> b) `RelativePanel` - requires additional changes to support references to other controls. So probably it makes sense to move this out of the PR.

I'll try to take a look next week

**Comment by JaggerJo** [comment]
Will merge this into master and continue from there

**Pull request merged**
