### PR TITLE
[WIP] Mockup of attr with list of attrs

### PR DESCRIPTION
**Pull request by Thecentury**
Hi @JaggerJo, what do you think about this idea?

It gives an ability to create custom methods returning a list of connected attrs — e.g., list with two subscriptions for `onChecked` and `onChecked` events,
or static-typed setting of both `ItemsControl.Items` and `ItemsTemplate`, where the type of an element of the `Items` gives the data type in the template.

Or any other example of creating a list of attributes from one piece of data.

### CODE REVIEW

**Comment by Thecentury** [comment]
Also it will allow to set no attributes conditionally, represented by a list with no elements:

```fsharp
let setSmth param =
  if param then
    Button.setSmth 1
  else
    Button.attrList []

Button.create [
  Button.content "Click"
]
```

If is possible to achieve the same now using `yield! some_possibly_empty_list_of_attributes`, but it has more verbose syntax.

**Comment by JaggerJo** [comment]
Hey @Thecentury,

sorry for the late response. 

If I understand your proposal correctly it basically enables you to add a list of attributes in the declaration, right ?

```fsharp

let reusableGroupOfAttributes : IAttr<Button> list =
    [
        Button.verticalAlignment VerticalAlignment.Center
        Button.horizontalAlignment HorizontalAlignment.Center
        Button.margin 20.0
    ]

let wrap (attrs: IAttr<'t> list) : 


Button.create [
    Button.background "green"
    Button.content "click me"
]
```

**Comment by Thecentury** [comment]
Hi @JaggerJo,

I already added something similar to `View.withAttrs` to my code, it works, but it looks not as setting properties in the native FuncUI way, a bit artificially.

I think, the change I propose can be shallow — we can create new type for inner attributes with the same set of possible values (property, content and subscription), and all implementation of Virtual DOM will remain unchanged. Conversion will happen at the edge, just in function creating view with attributes, as in my example.

I will try to implement this feature as a wrapper around existing API, just to check whether it is possible.

**Comment by Thecentury** [comment]
Hi @JaggerJo, should I close this PR?

**Comment by JaggerJo** [comment]
Hey @Thecentury , Yes sure. feel free to close it. Are you ok with the current solution ?

**Comment by Thecentury** [comment]
@JaggerJo Yes, I left the current solution. This idea was an improvement, and as I switched to another project I didn't have enough time and motivation to work on it.

**Comment by JaggerJo** [comment]
@Thecentury Let's keep this idea in mind. We might need to implement something like this in the future. 🙂

**Pull request closed without merging**
